# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movie-services/processmovies.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'movie-services/processmovies.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"movie-services/processmovies.proto\x12\x0cMovieService\"\x85\x01\n\tMovieInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\r\x12\r\n\x05genre\x18\x05 \x03(\t\x12\x0e\n\x06\x61\x63tors\x18\x06 \x03(\t\x12\x0f\n\x07summary\x18\x07 \x01(\t\x12\r\n\x05image\x18\x08 \x01(\t\"5\n\nMovieInfos\x12\'\n\x06Movies\x18\x01 \x03(\x0b\x32\x17.MovieService.MovieInfo\"k\n\x14ProcessMovieResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0fitems_processed\x18\x03 \x01(\x05\x12\x19\n\x11unprocessed_items\x18\x04 \x03(\t\"r\n\x16RecommendMoviesRequest\x12\x12\n\ntext_query\x18\x01 \x01(\t\x12\x0e\n\x06genres\x18\x02 \x03(\t\x12\x10\n\x08year_gte\x18\x03 \x01(\t\x12\x10\n\x08year_lte\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\r\"d\n\x17RecommendMoviesResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\'\n\x06Movies\x18\x03 \x03(\x0b\x32\x17.MovieService.MovieInfo2\x9a\x02\n\x0cMovieService\x12S\n\x14ProcessMovieSingular\x12\x17.MovieService.MovieInfo\x1a\".MovieService.ProcessMovieResponse\x12U\n\x15ProcessMoviesMultiple\x12\x18.MovieService.MovieInfos\x1a\".MovieService.ProcessMovieResponse\x12^\n\x0fRecommendMovies\x12$.MovieService.RecommendMoviesRequest\x1a%.MovieService.RecommendMoviesResponseB\x17Z\x15golang/movie-servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_services.processmovies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025golang/movie-services'
  _globals['_MOVIEINFO']._serialized_start=53
  _globals['_MOVIEINFO']._serialized_end=186
  _globals['_MOVIEINFOS']._serialized_start=188
  _globals['_MOVIEINFOS']._serialized_end=241
  _globals['_PROCESSMOVIERESPONSE']._serialized_start=243
  _globals['_PROCESSMOVIERESPONSE']._serialized_end=350
  _globals['_RECOMMENDMOVIESREQUEST']._serialized_start=352
  _globals['_RECOMMENDMOVIESREQUEST']._serialized_end=466
  _globals['_RECOMMENDMOVIESRESPONSE']._serialized_start=468
  _globals['_RECOMMENDMOVIESRESPONSE']._serialized_end=568
  _globals['_MOVIESERVICE']._serialized_start=571
  _globals['_MOVIESERVICE']._serialized_end=853
# @@protoc_insertion_point(module_scope)
