// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: movie-services/processmovies.proto

package movie_services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MovieService_ProcessMovie_FullMethodName  = "/MovieService.MovieService/ProcessMovie"
	MovieService_ProcessMovies_FullMethodName = "/MovieService.MovieService/ProcessMovies"
)

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieServiceClient interface {
	// Retrieves user information by ID.
	ProcessMovie(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*ProcessMovieResponse, error)
	// Creates a new user.
	ProcessMovies(ctx context.Context, in *MovieInfos, opts ...grpc.CallOption) (*ProcessMovieResponse, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) ProcessMovie(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*ProcessMovieResponse, error) {
	out := new(ProcessMovieResponse)
	err := c.cc.Invoke(ctx, MovieService_ProcessMovie_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) ProcessMovies(ctx context.Context, in *MovieInfos, opts ...grpc.CallOption) (*ProcessMovieResponse, error) {
	out := new(ProcessMovieResponse)
	err := c.cc.Invoke(ctx, MovieService_ProcessMovies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
// All implementations must embed UnimplementedMovieServiceServer
// for forward compatibility
type MovieServiceServer interface {
	// Retrieves user information by ID.
	ProcessMovie(context.Context, *MovieInfo) (*ProcessMovieResponse, error)
	// Creates a new user.
	ProcessMovies(context.Context, *MovieInfos) (*ProcessMovieResponse, error)
	mustEmbedUnimplementedMovieServiceServer()
}

// UnimplementedMovieServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMovieServiceServer struct {
}

func (UnimplementedMovieServiceServer) ProcessMovie(context.Context, *MovieInfo) (*ProcessMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMovie not implemented")
}
func (UnimplementedMovieServiceServer) ProcessMovies(context.Context, *MovieInfos) (*ProcessMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMovies not implemented")
}
func (UnimplementedMovieServiceServer) mustEmbedUnimplementedMovieServiceServer() {}

// UnsafeMovieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieServiceServer will
// result in compilation errors.
type UnsafeMovieServiceServer interface {
	mustEmbedUnimplementedMovieServiceServer()
}

func RegisterMovieServiceServer(s grpc.ServiceRegistrar, srv MovieServiceServer) {
	s.RegisterService(&MovieService_ServiceDesc, srv)
}

func _MovieService_ProcessMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).ProcessMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_ProcessMovie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).ProcessMovie(ctx, req.(*MovieInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_ProcessMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieInfos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).ProcessMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_ProcessMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).ProcessMovies(ctx, req.(*MovieInfos))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieService_ServiceDesc is the grpc.ServiceDesc for MovieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MovieService.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMovie",
			Handler:    _MovieService_ProcessMovie_Handler,
		},
		{
			MethodName: "ProcessMovies",
			Handler:    _MovieService_ProcessMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie-services/processmovies.proto",
}
