// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: movie-services/processmovies.proto

package movie_services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MovieService_ProcessMovieSingular_FullMethodName  = "/MovieService.MovieService/ProcessMovieSingular"
	MovieService_ProcessMoviesMultiple_FullMethodName = "/MovieService.MovieService/ProcessMoviesMultiple"
	MovieService_RecommendMovies_FullMethodName       = "/MovieService.MovieService/RecommendMovies"
)

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieServiceClient interface {
	ProcessMovieSingular(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*ProcessMovieResponse, error)
	ProcessMoviesMultiple(ctx context.Context, in *MovieInfos, opts ...grpc.CallOption) (*ProcessMovieResponse, error)
	RecommendMovies(ctx context.Context, in *RecommendMoviesRequest, opts ...grpc.CallOption) (*RecommendMoviesResponse, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) ProcessMovieSingular(ctx context.Context, in *MovieInfo, opts ...grpc.CallOption) (*ProcessMovieResponse, error) {
	out := new(ProcessMovieResponse)
	err := c.cc.Invoke(ctx, MovieService_ProcessMovieSingular_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) ProcessMoviesMultiple(ctx context.Context, in *MovieInfos, opts ...grpc.CallOption) (*ProcessMovieResponse, error) {
	out := new(ProcessMovieResponse)
	err := c.cc.Invoke(ctx, MovieService_ProcessMoviesMultiple_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieServiceClient) RecommendMovies(ctx context.Context, in *RecommendMoviesRequest, opts ...grpc.CallOption) (*RecommendMoviesResponse, error) {
	out := new(RecommendMoviesResponse)
	err := c.cc.Invoke(ctx, MovieService_RecommendMovies_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
// All implementations must embed UnimplementedMovieServiceServer
// for forward compatibility
type MovieServiceServer interface {
	ProcessMovieSingular(context.Context, *MovieInfo) (*ProcessMovieResponse, error)
	ProcessMoviesMultiple(context.Context, *MovieInfos) (*ProcessMovieResponse, error)
	RecommendMovies(context.Context, *RecommendMoviesRequest) (*RecommendMoviesResponse, error)
	mustEmbedUnimplementedMovieServiceServer()
}

// UnimplementedMovieServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMovieServiceServer struct {
}

func (UnimplementedMovieServiceServer) ProcessMovieSingular(context.Context, *MovieInfo) (*ProcessMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMovieSingular not implemented")
}
func (UnimplementedMovieServiceServer) ProcessMoviesMultiple(context.Context, *MovieInfos) (*ProcessMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMoviesMultiple not implemented")
}
func (UnimplementedMovieServiceServer) RecommendMovies(context.Context, *RecommendMoviesRequest) (*RecommendMoviesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecommendMovies not implemented")
}
func (UnimplementedMovieServiceServer) mustEmbedUnimplementedMovieServiceServer() {}

// UnsafeMovieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieServiceServer will
// result in compilation errors.
type UnsafeMovieServiceServer interface {
	mustEmbedUnimplementedMovieServiceServer()
}

func RegisterMovieServiceServer(s grpc.ServiceRegistrar, srv MovieServiceServer) {
	s.RegisterService(&MovieService_ServiceDesc, srv)
}

func _MovieService_ProcessMovieSingular_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).ProcessMovieSingular(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_ProcessMovieSingular_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).ProcessMovieSingular(ctx, req.(*MovieInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_ProcessMoviesMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieInfos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).ProcessMoviesMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_ProcessMoviesMultiple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).ProcessMoviesMultiple(ctx, req.(*MovieInfos))
	}
	return interceptor(ctx, in, info, handler)
}

func _MovieService_RecommendMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendMoviesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).RecommendMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MovieService_RecommendMovies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).RecommendMovies(ctx, req.(*RecommendMoviesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MovieService_ServiceDesc is the grpc.ServiceDesc for MovieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MovieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MovieService.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMovieSingular",
			Handler:    _MovieService_ProcessMovieSingular_Handler,
		},
		{
			MethodName: "ProcessMoviesMultiple",
			Handler:    _MovieService_ProcessMoviesMultiple_Handler,
		},
		{
			MethodName: "RecommendMovies",
			Handler:    _MovieService_RecommendMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie-services/processmovies.proto",
}
